### ISSUE TITLE
confluence.home isn't set if data_dir isn't parameter isn't set

### ISSUE THREAD

**Issue by kpankonen** [voxpupuli/puppet-confluence#111]
When data_dir isn't set, the confluence.home value in confluence-init.properties is set to an empty string

```puppet
<% if scope.lookupvar('confluence::data_dir') -%>
confluence.home=<%= scope.lookupvar('confluence::data_dir') %>
<% else %>
confluence.home=<%= scope.lookupvar('confluence::homedir') %>
<% end %>
```

tests with current master branch:
https://travis-ci.org/kpankonen/puppet-confluence/builds/199455533

tests using `scope.lookupvar('confluence::data_dir').empty?`
https://travis-ci.org/voxpupuli/puppet-confluence/builds/201574776

**Comment by Conzar** [comment]
I have confirmed this as well

**Comment by oranenj** [comment]
I'm pretty sure this is now fixed, so I will close the issue. Feel free to reopen if there's something missing
