### ISSUE TITLE
Module puppet/staging marked deprecated

### ISSUE THREAD

**Issue by ardrigh** [voxpupuli/puppet-confluence#123]
I see the [puppet/staging](https://github.com/voxpupuli/puppet-staging) module has been marked deprecated, and this module already uses [puppet-archive](https://github.com/voxpupuli/puppet-archive).

Is it a good time to remove the `puppet/staging` code references and dependency entry?

Ref: https://github.com/voxpupuli/puppet-staging/commit/251b6fa5b42da9e1970b7a15d20fddfbd800d616

**Comment by hdep** [comment]
According to the code default behavior is to use puppet-archive.

**Comment by ardrigh** [comment]
This ticket is very old so I have no idea if it's relevant any more.

**Comment by choffee** [comment]
puppet/staging is still in the metadata and code. Would be good to remove support.
