### ISSUE TITLE
Add systemd service file for RHEL7

### ISSUE THREAD

**Issue by mkrakowitzer** [voxpupuli/puppet-confluence#19]
Currently it works us the init script. Would be nice to use systemd service file instead.

**Comment by wouterhummelink** [comment]
This causes puppet 4.2 (PE 2015.02) to enable the service every run due to systemd responding differently for fake units

Notice: /Stage[main]/Confluence::Service/Service[confluence]/enable: enable changed 'false' to 'true'

**Comment by igalic** [comment]
fixed in #46
