### ISSUE TITLE
Support the mysql connector natively

### ISSUE THREAD

**Issue by tedivm** [voxpupuli/puppet-confluence#34]
In your jira module you have a "jira::mysql_connector" class that downloads the needed mysql java bindings. Can you do the same thing with this module so that the mysql java tools don't need to be manually installed?

**Comment by mkrakowitzer** [comment]
I actually have a module for this, https://github.com/mkrakowitzer/puppet-mysql_java_connector

I think it makes sense to support this inside the module, will add it.

**Comment by ffrank** [comment]
Er, will you be maintaining essentially the same functionality in 3 modules then?

Should not both `jira` and `confluence` depend on `mysql_java_connector` instead?

**Comment by tedivm** [comment]
I just like the feature, I'm not sure I care how it's supported. That being said I see @ffrank's point. Maybe it's time for a generic atlassian project to handle the common stuff and help keep parity between the jira and confluence projects.

**Comment by mkrakowitzer** [comment]
Absolutely, jira, stash and confluence should depend on this module to provide the java mysql connector

**Comment by kwolf** [comment]
for what it's worth, we use the mysql::bindings::java to pull in the bindings.

**Comment by igalic** [comment]
hmm…

**Comment by mkrakowitzer** [comment]
I originally had issues using the mysql::binding::java class because the packages that ship with RHEL6 and Ubuntu 12.04 have known compatibility issues. Atlassian recommend using the latest upstream version from oracle/mysql. So I think this would still be a valid issue and I should add this support.

**Comment by igalic** [comment]
:+1:

different use-case, makes sense to use a different dependency then.

**Comment by jyaworski** [comment]
Hello: What's the status of this?

**Comment by Tokynet** [comment]
BUMP?

**Comment by igalic** [comment]
i think the status is: "patches welcome" ☹

**Comment by Tokynet** [comment]
I'll look into this today and over the weekend. Using the puppet-mysql_java_connector module breaks confluence IF you try to link the connector into the appropriate directory (confluence installdir/appversion/confluence/WEB-INF/lib).


Basically, if you apply the code below (and trigger a confluence restart) tomcat will not start back up at all:

```
class { 'confluence':
  version           => $confluencever,
  installdir         => '/data/apps/confluence-install',
  homedir         => '/data/apps/confluence-home',
  javahome       => $javahome,
}

class { 'mysql_java_connector':
  links   => ["/data/apps/confluence-install/atlassian-confluence-${confluencever}/confluence/WEB-INF/lib"],
  version => '5.1.41',
  require => Class['confluence'],
}

```
I've tested that this does not work even if I keep the (confluence) module's default path for home and installdirs and I try to link the java connector into that new path.

**Comment by ffrank** [comment]
@Tokynet cool, thanks! Do you require any help debugging this, or are you still on top of things?

**Comment by Tokynet** [comment]
@ffrank I got too involved with our atlassian setup... I will circle back for this probably tomorrow.
For my situation, i just added a file resource that took the connector(file) from where the mysql_java_connector module put it and moved it to the right place. Not pretty but it worked.
Not elegant though.

**Comment by ffrank** [comment]
Great, so in essence, you will have to find out why your original approach of using the module did not Just Work.
Good luck, looking forward to a possible patch once you figured it out :+1:

**Comment by hdep** [comment]
hi, is there any change since 2017 about this issue ? 
i'm facing the same : confluence ask for the mysql lib connector.

**Comment by tedivm** [comment]
I gave up and moved to the cloud hosted version ;-)

**Comment by hdep** [comment]
I can understand, today I spend more time digging the module than I should have to deploy it manually. 
That's the devops life  :)
