### ISSUE TITLE
Support for Puppet 4

### ISSUE THREAD

**Issue by luke-vidler** [voxpupuli/puppet-confluence#39]
Hello, 

Can Confirm this module is not working with Puppet 4.2.1.  Any idea when it will be? Happy to help in any way.

Thanks.

**Comment by bountin** [comment]
I'm also using Puppet 4.2.1 and it's working but I'm not using hiera but the traditional class configuration in my node.pp.

**Comment by luke-vidler** [comment]
Hi Martin,

I'm trying to deploy to a RHEL 6 (latest updates) server. Would it be possible for you to share your Config ?   Here is what I have:

  class {  'confluence': 
    version      => '5.8.7',
    installdir     => '/opt/atlassian/confluence',
    homedir     => '/opt/atlassian/confluence-home',
    javahome  => '/usr/lib/jvm/jre-1.7.0-openjdk.x86_64', 
    user           => 'confluence',
    group         => 'confluence',
  }

**Comment by bountin** [comment]
Okay, I'm deploying to Ubuntu 14.04 with the following more simple config:
```
  class { 'confluence':
    javahome => '/usr/lib/jvm/java-7-openjdk-amd64',
    tomcat_proxy => { scheme => 'https', proxyName => 'XXX', proxyPort => 443, },
  }
```
It successfully downloads and creates the confluence installation and starts it.

**Comment by mkrakowitzer** [comment]
I'll confirm support for puppet 4 in the spec/acceptance tests soon.

@luke-vidler what you have there looks good. I assume you have made sure /opt/atlassian parent directory has been created? If you are getting an error, please feel free to post it here and ill see if I can help.

**Comment by igalic** [comment]
i think a simple start would be to add support in puppet-rspec tests!

**Comment by luke-vidler** [comment]
Hi Mark, 

Was able to revisit this, works perfectly on RHEL 6.7 with Puppet Enterprise 2015.2 (4.2.1). Its a nice module, thanks :)

**Comment by igalic** [comment]
@mkrakowitzer time to close this?

**Comment by mkrakowitzer** [comment]
@igalic Would be nice to add the modulesync stuff you guys been working on that I assume supports testing on puppet v4 and then close this? I just can not figure out how to use it :(

**Comment by igalic** [comment]
@mkrakowitzer wanna hop on IRC, and we discuss it?
add confluence, then document it?

**Comment by mkrakowitzer** [comment]
sure
