### ISSUE TITLE
Support for debian jessie

### ISSUE THREAD

**Issue by pdirksen** [voxpupuli/puppet-confluence#53]
`/etc/init.d/confluence start`

```
[....] Starting confluence (via systemctl): confluence.serviceFailed to start confluence.service: Unit confluence.service failed to load: No such file or directory.
 failed!
```

Please add support for debian jessie.

**Comment by jyaworski** [comment]
Can you be more specific? Is it that Confluence doesn't come with a .service file, and this module should provide it?

**Comment by pdirksen** [comment]
Manifest look okayish. This is a bug report then. 
I had Confluence installed using this puppet template. Starting Confluence via start script works but starting via the service command doesn't and instead the error above appears.

**Comment by ricciocri** [comment]
To use the "old" /etc/init.d/file you have to issue a reload of systemd (on Debian 8 or any systemd Linux) with systemctl daemon-reload  

After that it will works fine

**Comment by hdep** [comment]
Hi,
Jessie is obsolete now.
